### ISSUE TITLE
[Suggestion] Sub-command and argument to poll NBT data, plus flag/highlight

### ISSUE THREAD

**Issue by Aedda** [malte0811/NBTEdit#2]
It could be useful to have a usage of the command such as "/nbtedit poll 20" and this would re-read the nbt data every 20 ticks and display in the same window.

Additionally to that it could be useful to be able to select an entry in the window to keep focused and highlighted at all times.

**Comment by malte0811** [comment]
I have implemented the first part of your suggestion (pulling NBT data from the world every n ticks), as a button in the GUI instead of a sub command though. I don't recommend setting the time below ~5-10 ticks as low delays cause flickering in the GUI (might be fixable, I don't use Swing a lot).
What do you mean by the second part? Are you talking about entries un-selecting when pulling NBT data (that should be fixed by the above commit)? Or do you want the ability to highlight NBT elements independent of the "official" selection (`JTree.getSelectionPath()`)?

**Comment by malte0811** [comment]
@Aedda Unless you have replied by then I will publish a build without the second part of your request tomorrow and close this issue.

> What do you mean by the second part? Are you talking about entries un-selecting when pulling NBT data (that should be fixed by the above commit)? Or do you want the ability to highlight NBT elements independent of the "official" selection (`JTree.getSelectionPath()`)?

**Comment by Aedda** [comment]
Oh sorry I did not see a notice of a reply. I mean for instance I took a mob and used /nbtedit on it. I then scrolled down to where in the NBT its health was. Returned to the game, and began damaging it. Went back to the NBT window and hit pull NBT from world and the list scrolled to the top, hiding the health value. I would like if I could set it so the selected tag is always visible within the window.

Ideally I like to be able to flag more than one tag to have displayed or mirrored separately but that is on a different scale than my initial suggestion.
